apiVersion: v1
kind: Pod
metadata:
  name: elapsed
  namespace: default
  labels:
    app.kubernetes.io/name: elapsed
    app.kubernetes.io/instance: elapsed-singleton
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: server
spec:
  containers:
  - name: elapsed-server
    image: docker.io/bion/elapsed:latest
    imagePullPolicy: Always
    env:
    - name: DB_FILE_PATH
      value: /data/elapsed.db
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 8080
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: elapsed-local-path-pvc
